In [2]:
import tensorflow as tf 

# Basics 

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2,0,4,5,-3])
print(tensor_one_d)

tf.Tensor([ 2  0  4  5 -3], shape=(5,), dtype=int32)


In [5]:
tensor_two_d =tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [6]:
tensor_three_d = tf.constant([
    [[1,2,3],
      [4,5,6]],
    [[5,6,7],
      [4,7,8]],
    [[9,7,0],
      [1,4,5]]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [4 7 8]]

 [[9 7 0]
  [1 4 5]]], shape=(3, 2, 3), dtype=int32)


In [7]:
print(tensor_three_d.shape)

(3, 2, 3)


In [8]:
import numpy as np

In [10]:
np_array = [2,3,4,5]
print(np_array)

[2, 3, 4, 5]


In [11]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [24]:
eye_tensor = tf.eye(num_rows = 5,
                   num_columns =None,
                   batch_shape = [3,2],
                   dtype = tf.dtypes.float32,
                    name = None 
                   )

In [25]:
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(3, 2, 5, 5), dtype=float32)


eye method gives the identity matrix.

In [30]:
fill_tensor = tf.fill(
    [2,3,3],4,name = None )
print(fill_tensor)

tf.Tensor(
[[[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]], shape=(2, 3, 3), dtype=int32)


In [31]:
ones_tensor = tf.ones(
   [2,3], dtype = tf.dtypes.float32)

In [32]:
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [33]:
ones_like = print(tf.ones_like(fill_tensor))

tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(2, 3, 3), dtype=int32)


In [37]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 97.920235 100.819534]
 [101.22446   99.98016 ]
 [ 99.813675 100.32449 ]], shape=(3, 2), dtype=float32)


# INDEXING

In [44]:
tensor_indexed = tf.constant([3,4,5,6,7,])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[2:-1])
print(tensor_indexed[1:5:2])

tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int32)
tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)


In [41]:
tf.range(3,7)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 6])>

In [50]:
tensor_two_d =tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)


# Tensor and variables

In [3]:
x_abs = tf.abs([-2,3,4,6])
print(x_abs)

tf.Tensor([2 3 4 6], shape=(4,), dtype=int32)


In [7]:
x_1 = tf.constant([2,3,4,5,6],dtype = tf.float32)
x_2 = tf.constant([6,7,8,9,0],dtype = tf.float32)
print(tf.math.add(x_1,x_2))
print(tf.math.multiply(x_1,x_2))

tf.Tensor([ 8. 10. 12. 14.  6.], shape=(5,), dtype=float32)
tf.Tensor([12. 21. 32. 45.  0.], shape=(5,), dtype=float32)


In [8]:
print(tf.math.argmax(x_1))

tf.Tensor(4, shape=(), dtype=int64)


It gives the index of the maximum values.

In [10]:
x = tf.constant([3,4])
y = tf.constant([4,5])
print(tf.pow(x,y))

tf.Tensor([  81 1024], shape=(2,), dtype=int32)


# Linear Algebra

In [17]:
x_1 = tf.constant([[1,2,3],[4,5,6]])
x_2 = tf.constant([[2,3],[1,2],[4,5]])
print(x_1.shape,x_2.shape)

(2, 3) (3, 2)


In [18]:
tf.linalg.matmul(x_1, x_2,
                 transpose_b=False,
                 adjoint_a=False,
                 adjoint_b=False,
                 a_is_sparse=False,
                 b_is_sparse=False,
                 output_type=None,
                 name=None)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 22],
       [37, 52]])>

In [19]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [22]:
!git add .


In [23]:
!git commit -m "completed"

[main 21bbbee] completed
 1 file changed, 172 insertions(+), 1 deletion(-)


In [24]:
!git push origin main

remote: This repository moved. Please use the new location:        
remote:   https://github.com/jyotiraut/DeepLearning.git        
To https://github.com/jyotiraut/Computer_Vision.git
   2da34db..21bbbee  main -> main
