In [2]:
import tensorflow as tf 

# Basics 

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2,0,4,5,-3])
print(tensor_one_d)

tf.Tensor([ 2  0  4  5 -3], shape=(5,), dtype=int32)


In [5]:
tensor_two_d =tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [6]:
tensor_three_d = tf.constant([
    [[1,2,3],
      [4,5,6]],
    [[5,6,7],
      [4,7,8]],
    [[9,7,0],
      [1,4,5]]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [4 7 8]]

 [[9 7 0]
  [1 4 5]]], shape=(3, 2, 3), dtype=int32)


In [7]:
print(tensor_three_d.shape)

(3, 2, 3)


In [8]:
import numpy as np

In [10]:
np_array = [2,3,4,5]
print(np_array)

[2, 3, 4, 5]


In [11]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [24]:
eye_tensor = tf.eye(num_rows = 5,
                   num_columns =None,
                   batch_shape = [3,2],
                   dtype = tf.dtypes.float32,
                    name = None 
                   )

In [25]:
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(3, 2, 5, 5), dtype=float32)


eye method gives the identity matrix.

In [30]:
fill_tensor = tf.fill(
    [2,3,3],4,name = None )
print(fill_tensor)

tf.Tensor(
[[[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]], shape=(2, 3, 3), dtype=int32)


In [31]:
ones_tensor = tf.ones(
   [2,3], dtype = tf.dtypes.float32)

In [32]:
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [33]:
ones_like = print(tf.ones_like(fill_tensor))

tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(2, 3, 3), dtype=int32)


In [37]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 97.920235 100.819534]
 [101.22446   99.98016 ]
 [ 99.813675 100.32449 ]], shape=(3, 2), dtype=float32)


# INDEXING

In [44]:
tensor_indexed = tf.constant([3,4,5,6,7,])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[2:-1])
print(tensor_indexed[1:5:2])

tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int32)
tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)


In [41]:
tf.range(3,7)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 6])>

In [50]:
tensor_two_d =tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)


# Tensor and variables