In [7]:
import numpy as np

In [8]:
 a = np.array([[2,3,4],
             [6,7,8]])
    
 b = np.array([[2,3],[3,4],[6,7]])

In [9]:
print(a.shape)
print(b.shape)
print(np.matmul(a,b))

(2, 3)
(3, 2)
[[ 37  46]
 [ 81 102]]


Einsum

In [11]:
print("Einsum: C")
print(np.einsum("ij,jk->ik",a,b))

Einsum: C
[[ 37  46]
 [ 81 102]]


In [12]:
print("Einsum Transpose:")
print(np.einsum("ij->ji",a))

Einsum Transpose:
[[2 6]
 [3 7]
 [4 8]]


# Common Functions in Tenserflow

In [31]:
import tensorflow as tf
x = tf.constant([2,3,4])
print(x.shape)
print(tf.expand_dims(x,axis=0))

(3,)
tf.Tensor([[2 3 4]], shape=(1, 3), dtype=int32)


In [17]:
x = tf.constant([[2,3,4],[4,5,6]])
print(tf.reshape(x,[-1]))

tf.Tensor([2 3 4 4 5 6], shape=(6,), dtype=int32)


In [18]:
a = tf.constant([1, 2])
b = tf.constant([3, 4])

In [19]:
result = tf.stack([a, b])

In [27]:
x = tf.ragged.constant([[1, 2, 4], [3, 4]])  
print(x)

<tf.RaggedTensor [[1, 2, 4], [3, 4]]>


In [29]:
print(x)

<tf.RaggedTensor [[1, 2, 4], [3, 4]]>


In [33]:
s = tf.constant(["hell", "world"])
tf.strings.length(s)



<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5])>

In [34]:
st = tf.sparse.SparseTensor(indices=[[0, 1], [2, 3]],
                            values=[10, 20],
                            dense_shape=[3, 4])



In [35]:
print(st)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [41]:
x = tf.constant([[1, 2], [3, 4]])
padded = tf.pad(x, paddings=[[1, 2], [2, 3]], constant_values=0)

In [42]:
print(padded)

tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 1 2 0 0 0]
 [0 0 3 4 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]], shape=(5, 7), dtype=int32)


In [46]:
x = tf.constant([[10, 11], [20, 21], [30, 31]])
result = tf.gather(x, indices=[0, 1])

In [47]:
print(result)

tf.Tensor(
[[10 11]
 [20 21]], shape=(2, 2), dtype=int32)


In [53]:
x = tf.constant([[[1,2], [2,2], [3,4]]])
print(x.shape)
squeezed = tf.squeeze(x)
print(squeezed.shape)
print(squeezed)

(1, 3, 2)
(3, 2)
tf.Tensor(
[[1 2]
 [2 2]
 [3 4]], shape=(3, 2), dtype=int32)


In [64]:
x = tf.constant([[1, 2,4], [3, 4,5]])
reshaped = tf.reshape(x, shape=(3,2))
print(reshaped)

tf.Tensor(
[[1 2]
 [4 3]
 [4 5]], shape=(3, 2), dtype=int32)


# Variables

In [65]:
v = tf.Variable(10)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [66]:
v.assign(20)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>


In [67]:
v.assign_add(4)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=24>


In [70]:
w = tf.Variable([2.0, 3.0])
b = tf.Variable([0.5, -0.5])
output = w * 3 + b
print(output.numpy())


[6.5 8.5]


In [ ]:
!git add .
